config/routes.rb
Rails.application.routes.draw do
  get 'cart/add'
  get 'cart/index'
  get 'cart/remove'
  get 'cart/clear'

  devise_for :users
  resources :products

  root 'products#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  acts_as_shopping_cart_using :cart_item
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  acts_as_shopping_cart_item_for :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :cart

  def is_admin?
    self.is_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_filter :authenticate_user!
  before_filter :helper

  def add
    @product = Product.find(params[:id])
    current_user.cart.add(@product, @product.price)
    redirect_to :cart_index
  end

  def remove
    @product = Product.find(params[:id])
    current_user.cart.remove(@product, 1)
    redirect_to :cart_index
  end

  def index
    @cart = current_user.cart
  end

  def clear
    current_user.cart.clear
    redirect_to :cart_index
  end

  private
    def helper
      unless current_user.cart
        current_user.cart = Cart.create
        current_user.save
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :is_admin, only: [:edit, :new, :update, :destroy]
  before_filter :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(:page => params[:page])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end

    def is_admin
      unless current_user.is_admin?
        redirect_to :products
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1>Your Shopping Cart</h1>

<table>
  <thead>
    <tr>
      <th class="col-xs-6">Name</th>
      <th class="col-xs-4">Price</th>
      <th class="col-xs-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart.shopping_cart_items.each do |item| %>
      <tr>
        <td class="col-xs-6"><%= item.item.name %></td>
        <td class="col-xs-4"><%= item.item.id %></td>
        <td class="col-xs-1">
          <%= link_to 'Show', item.item, :class => 'btn-xs btn-info' %>
        </td>
        <td class="col-xs-1">
          <%= link_to 'Remove', cart_remove_path(id: item.item.id), :class => 'btn-xs btn-warning' %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td><%= link_to 'Checkout', cart_clear_path, :class => 'btn-xs btn-success', data: { confirm: 'Do you want this free?' } %></td>
      <td><%= link_to 'Clear Cart', cart_clear_path, :class => 'btn-xs btn-danger', data: { confirm: 'Are you sure?' } %></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Luo Store</title>
    <%= javascript_include_tag :defaults %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
<%= nav_bar :fixed => :top, :brand => "LuoStore", :responsive => true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_divider %>
        <%= drop_down "Products" do %>
            <%= menu_item "All Products", products_path %>
            <% if current_user %>
              <% if current_user.is_admin? %>
                 <%= menu_item "Add Product", new_product_path %>
              <% end %>
            <% end %>
        <% end %>
        <%= menu_divider %>
        <%= menu_item "Cart", cart_index_path %>
    <% end %>
    <%= menu_group :pull => :right do %>
        <% if current_user %>
            <%= menu_item "Log Out", destroy_user_session_path, :method => :delete %> 
        <% else %>
            <%= menu_item "Log In", new_user_session_path %>
            <%= menu_divider %>
            <%= menu_item "Sign Up", new_user_registration_path %>
        <% end %>
    <% end %>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="col-xs-12">
    <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>All Products</h1>

<table>
  <thead>
    <tr>
      <th class="col-xs-5">Name</th>
      <th class="col-xs-3">Price</th>
      <th class="col-xs-1"></th>
    </tr>
  </thead>

  <tbody>
    <%= will_paginate @products %>
    <% @products.each do |product| %>
      <tr>
        <td class="col-xs-5"><%= product.name %></td>
        <td class="col-xs-3"><%= product.price %></td>
        <td class="col-xs-1"><%= link_to 'Show', product, :class => 'btn-xs btn-info' %></td>
        <% if current_user %>
          <% if current_user.is_admin? %>
            <td class="col-xs-1"><%= link_to 'Edit', edit_product_path(product), :class => 'btn-xs btn-warning' %></td>
            <td class="col-xs-1"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn-xs btn-warning' %></td>
          <% end %>
        <% end %>
        <td class="col-xs-1"><%= link_to 'Add to Cart', cart_add_path(id: product.id), :class => 'btn-xs btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
  <% if current_user.is_admin? %>
    <%= link_to 'New Product', new_product_path, :class => 'btn-xs btn-primary' %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<% if current_user %>
  <% if current_user.is_admin? %>
    <%= link_to 'Edit', edit_product_path(@product) %> |
  <% end %>
<% end %>
<%= link_to 'Back', products_path %>